services:
  backend:
    build: ./backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command:
      - watchmedo
      - auto-restart
      - --directory=/app
      - --pattern=*.py
      - --recursive
      - --debug-force-polling
      - --
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8002
      - --noreload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=150
    command: npm run dev -- --host 0.0.0.0 --port 5173 --strictPort
    depends_on:
      - backend
